branch-defaults:
  master:
    environment: ENV-crud_app
global:
  application_name: crud_app
  default_ec2_keyname: orchard_admin
  default_platform: null
  default_region: null
  profile: null
  sc: git
deploy:
  artifact: crud_app.zip
